version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      # Set permissions.
      - chmod a+x qb

      # Build the project.
      - ./qb build --env=$ENVIRONMENT

      # Assemble the bundle.
      - npm install --production
      - mkdir bundle

      - cp package.json bundle/
      - cp tsconfig.json bundle/
      - cp tsconfig-paths-bootstrap.js bundle/
      - cp -r dist bundle/
      - cp -r node_modules bundle/

      # Compress the bundle.
      - zip -r bundle.zip bundle/*
      - cat package.json
artifacts:
  files:
    - bundle.zip
