version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      # Set permissions.
      - chmod a+x qb

      # Build the project.
      - ./qb build --env=$ENVIRONMENT

      # Assemble the bundle.
      - npm install --production

      - mkdir -p bundle
      - cp dist/server/server.js bundle/
      - cd bundle

      # Compress the bundle.
      - zip ../bundle.zip server.js
      - cd ..
artifacts:
  files:
    - bundle.zip
