version: 0.2

phases:
  install:
    commands:
      - npm i
  build:
    commands:
      # Set permissions.
      - chmod a+x qb
      - chmod a+x ./node_modules/@angular/cli/bin/ng
      - chmod a+x ./node_modules/webpack-cli/bin/cli.js
      - chmod a+x ./node_modules/ts-node/dist/bin.js

      # Build the project.
      - ./qb build --env=$ENVIRONMENT

      - mkdir -p tmp

      - cp package.json tmp/
      - cp tsconfig.json tmp/
      - cp tsconfig-paths-bootstrap.js tmp/
      - cp -r dist tmp/

      # - cp dist/server/server.js tmp/
      - cd tmp
      - npm i --production

      # Compress the bundle.
      # - zip ../bundle.zip server.js
      # - zip -r ../bundle.zip *
artifacts:
  base-directory: 'tmp'
  files:
    # - bundle.zip
    - '**/*'
  
