#!/usr/bin/env node
const { resolve } = require('path')
const { exec } = require('shelljs')
const { mkdirp, copySync } = require('fs-extra')
const minimist = require('minimist')
const boxen = require('boxen')

require('dotenv').config({ path: resolve(process.cwd(), '.variables') })
if (!process.env.ENVIRONMENT && !process.env.PORT) {
  require('dotenv').config()
}

main()
function main() {
  const {
    _: [ action, ...modifiers ],
    environment: _environment,
    skipTests,
  } = minimist(process.argv.slice(2), {
    string: [
      'environment',
    ],
    boolean: [
      'skip-tests'
    ],
    alias: {
      env: 'environment',
      skipTests: 'skip-tests',
    },
  })
  const environment = _environment || 'development'

  if (action === 'test') {
    const [ stack, modifier ] = modifiers
    test(stack, modifier, skipTests)
  }

  if (action === 'build') {
    const [ stack ] = modifiers
    build(stack, environment, skipTests)
  }

  if (action === 'dev') {
    const [ stack ] = modifiers
    dev(stack)
  }

  if (action === 'help' || !action) {
    help()
  }
}

function test(stack, modifier, skipTests) {
  if (skipTests) {
    return
  }

  if (stack === 'ui') {
    if (modifier) {
      if (modifier === 'unit') {
        exec('./node_modules/jest/bin/jest --config ./jest.ui-unit.config.js')
      }
      if (modifier === 'e2e') {
        exec('./node_modules/@angular/cli/bin/ng e2e')
      }
    }
    else {
      test('ui', 'unit', skipTests)
    }
  }

  if (stack === 'server') {
    // TODO: maybe add --watch and --coverage.
    exec('./node_modules/jest/bin/jest --config ./server/test/jest-unit.config.js')
  }
}

function generate(fileKey) {
  if (fileKey) {
    if (fileKey === 'app-config') {
      exec('./node_modules/ts-node/dist/bin.js common/src/code-gen/generate-app-config.ts')
    }
    if (fileKey === 'angular-data-services') {
      exec('./node_modules/ts-node/dist/bin.js common/src/code-gen/generate-angular-data-services.ts')
    }
  }
  else {
    generate('app-config')
    generate('angular-data-services')
  }
}

function prebuild(stack, env, skipTests) {
  if (stack === 'ui') {
    generate('app-config')
    generate('angular-data-services')
  }
  if (stack === 'server') {
    generate('app-config')
  }

  if (env && env === 'production') {
    test(stack, undefined, skipTests)
  }
}

function build(stack, env, skipTests) {
  prebuild(stack, env, skipTests)

  if (stack) {
    if (stack === 'ui') {
      exec(`./node_modules/@angular/cli/bin/ng build web --configuration=${env} && ./node_modules/@angular/cli/bin/ng run web:ssr:${env}`)
    }
    if (stack === 'server') {
      // exec(`./node_modules/webpack-cli/bin/cli.js`)
      exec(`tsc -p server/tsconfig.server.json`)
      mkdirp(resolve(__dirname, './dist/server/server/src/domains/email/emails/templates'))
      copySync(
        './server/src/domains/email/emails/templates/.',
        './dist/server/server/src/domains/email/emails/templates',
        { recursive: true }
      )
      copySync(
        './server/src/domains/email/emails/partials/.',
        './dist/server/server/src/domains/email/emails/partials',
        { recursive: true }
      )
      copySync(
        './work-files/.',
        './dist/server/work-files',
        { recursive: true }
      )
    }
  }
  else {
    build('ui', env, skipTests)
    build('server', env, skipTests)
  }
}

function dev(stack) {
  if (stack) {
    prebuild(stack)
    if (stack === 'ui') {
      exec('./node_modules/@angular/cli/bin/ng serve')
    }
    if (stack === 'server') {
      exec('nodemon --config nodemon.json')
    }
  }
  else {
    dev('ui')
    dev('server')
  }
}

function help() {
  const usage = `Usage of 'qb':

  Develop:        qb dev [ui|server]
  Build:          qb build <ui|server|all> <development|production>
  Test:           qb test ui [unit|e2e]
                  qb test server [unit] [watch|cov]
  Code gen:       qb generate`

  console.log(
    boxen(usage, {
      padding: 1,
      align: 'left',
    })
  )
}


