import { writeFileSync } from 'fs'
import { resolve } from 'path'

const buildEnv = process.env.ENVIRONMENT
const appConfig = require(`../../../app-config.${buildEnv.toLowerCase()}.json`)
const libPathToAppConfig = resolve(__dirname, '../lib/config/app.config.ts')
const formatJsonValue = (value: any) => typeof value === 'string'
  ? `'${value}'`
  : value

const appConfigClass = `// THIS FILE IS GENERATED. Do not edit this file.
export class AppConfig {${
    Object.keys(appConfig)
      .map((key) =>
        '\n  public static readonly ' + key + ' = ' + formatJsonValue(appConfig[key])
      )
      .join('')
  }
}\n`

writeFileSync(libPathToAppConfig, appConfigClass)
