// THIS FILE IS GENERATED. Do not edit this file.
import { forwardRef, Module } from '@nestjs/common'
import { TypeOrmModule } from '@nestjs/typeorm'
import { Product } from '@qb/common/api/entities/product'
import { AttributeValueModule } from '../attribute-value/attribute-value.module.generated'
import { AttributeModule } from '../attribute/attribute.module.generated'
import { CartModule } from '../cart/cart.module.generated'
import { DiscountModule } from '../discount/discount.module.generated'
import { DomainEventModule } from '../domain-event/domain-event.module.generated'
import { OrderModule } from '../order/order.module'
import { OrganizationModule } from '../organization/organization.module.generated'
import { OrganizationService } from '../organization/organization.service'
import { TaxonomyTermModule } from '../taxonomy-term/taxonomy-term.module.generated'
import { TaxonomyModule } from '../taxonomy/taxonomy.module.generated'
import { UserModule } from '../user/user.module'
import { WishlistModule } from '../wishlist/wishlist.module.generated'
import { ProductController } from './product.controller'
import { ProductRepository } from './product.repository.generated'
import { ProductService } from './product.service'

@Module({
  imports: [
    forwardRef(() => AttributeModule),
    forwardRef(() => AttributeValueModule),
    forwardRef(() => CartModule),
    forwardRef(() => DiscountModule),
    forwardRef(() => DomainEventModule),
    forwardRef(() => OrderModule),
    forwardRef(() => OrganizationModule),
    forwardRef(() => TaxonomyModule),
    forwardRef(() => TaxonomyTermModule),
    forwardRef(() => UserModule),
    forwardRef(() => WishlistModule),
    TypeOrmModule.forFeature([ Product ]),
  ],
  providers: [
    ProductRepository,
    ProductService,
    OrganizationService,
  ],
  controllers: [ ProductController ],
  exports: [
    ProductRepository,
    ProductService,
  ],
})
export class ProductModule { }
