// THIS FILE IS GENERATED. Do not edit this file.
import { forwardRef, Module } from '@nestjs/common'
import { TypeOrmModule } from '@nestjs/typeorm'
import { User } from '@qb/common/api/entities/user'
import { AttributeValueModule } from '../attribute-value/attribute-value.module.generated'
import { AttributeModule } from '../attribute/attribute.module.generated'
import { CartModule } from '../cart/cart.module.generated'
import { DiscountModule } from '../discount/discount.module.generated'
import { DomainEventModule } from '../domain-event/domain-event.module.generated'
import { OrderModule } from '../order/order.module'
import { OrganizationModule } from '../organization/organization.module.generated'
import { ProductModule } from '../product/product.module'
import { TaxonomyTermModule } from '../taxonomy-term/taxonomy-term.module.generated'
import { TaxonomyModule } from '../taxonomy/taxonomy.module.generated'
import { WishlistModule } from '../wishlist/wishlist.module.generated'
import { UserController } from './user.controller'
import { UserRepository } from './user.repository.generated'
import { UserService } from './user.service'

@Module({
  imports: [
    forwardRef(() => AttributeModule),
    forwardRef(() => AttributeValueModule),
    forwardRef(() => CartModule),
    forwardRef(() => DiscountModule),
    forwardRef(() => DomainEventModule),
    forwardRef(() => OrderModule),
    forwardRef(() => OrganizationModule),
    forwardRef(() => ProductModule),
    forwardRef(() => TaxonomyModule),
    forwardRef(() => TaxonomyTermModule),
    forwardRef(() => WishlistModule),
    TypeOrmModule.forFeature([ User ]),
  ],
  providers: [ UserRepository, UserService ],
  controllers: [ UserController ],
  exports: [ UserRepository, UserService ],
})
export class UserModule { }
