// THIS FILE IS GENERATED. Do not edit this file.
import { HttpClient } from '@angular/common/http'
import { Injectable } from '@angular/core'
import { DataService } from './data.service'

import { Cart } from '../../api/entities/cart'
import { Discount } from '../../api/entities/discount'
import { DomainEvent } from '../../api/entities/domain-event'
import { Order } from '../../api/entities/order'
import { Organization } from '../../api/entities/organization'
import { Product } from '../../api/entities/product'
import { TaxonomyTerm } from '../../api/entities/taxonomy-term'
import { User } from '../../api/entities/user'

import { carts } from '../../constants/api-endpoints'
import { discounts } from '../../constants/api-endpoints'
import { domainEvents } from '../../constants/api-endpoints'
import { orders } from '../../constants/api-endpoints'
import { organizations } from '../../constants/api-endpoints'
import { products } from '../../constants/api-endpoints'
import { taxonomyTerms } from '../../constants/api-endpoints'
import { users } from '../../constants/api-endpoints'

@Injectable({ providedIn: 'root' })
export class CartDataService extends DataService<Cart> {
  public readonly baseEndpoint = carts
  constructor(protected readonly _httpClient: HttpClient) { super() }
}

@Injectable({ providedIn: 'root' })
export class DiscountDataService extends DataService<Discount> {
  public readonly baseEndpoint = discounts
  constructor(protected readonly _httpClient: HttpClient) { super() }
}

@Injectable({ providedIn: 'root' })
export class DomainEventDataService extends DataService<DomainEvent> {
  public readonly baseEndpoint = domainEvents
  constructor(protected readonly _httpClient: HttpClient) { super() }
}

@Injectable({ providedIn: 'root' })
export class OrderDataService extends DataService<Order> {
  public readonly baseEndpoint = orders
  constructor(protected readonly _httpClient: HttpClient) { super() }
}

@Injectable({ providedIn: 'root' })
export class OrganizationDataService extends DataService<Organization> {
  public readonly baseEndpoint = organizations
  constructor(protected readonly _httpClient: HttpClient) { super() }
}

@Injectable({ providedIn: 'root' })
export class ProductDataService extends DataService<Product> {
  public readonly baseEndpoint = products
  constructor(protected readonly _httpClient: HttpClient) { super() }
}

@Injectable({ providedIn: 'root' })
export class TaxonomyTermDataService extends DataService<TaxonomyTerm> {
  public readonly baseEndpoint = taxonomyTerms
  constructor(protected readonly _httpClient: HttpClient) { super() }
}

@Injectable({ providedIn: 'root' })
export class UserDataService extends DataService<User> {
  public readonly baseEndpoint = users
  constructor(protected readonly _httpClient: HttpClient) { super() }
}
